# Generated by Django 4.1 on 2022-08-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evento_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
    ]
